### PR TITLE
Fix recent posts showing

### PR DESCRIPTION
**Pull request by boh717**
## What problem does this PR solve?

Content pages are not filtered in recent posts in home page.

image

You're not seeing this issue in the demo because:
- You have 5 posts published
- About page date is older than all posts

`posts` wasn't affected by this issue, only home.

## Is this PR related to any issue or discussion?

I didn't open an issue.

## PR Checklist

- [X] I have verified that the code works as described/as intended.
- [ ] This change adds a social icon which has a permissive license to use it.
- [X] This change **does not** include any external library/resources.
- [X] This change **does not** include any unrelated scripts (e.g. bash and python scripts).
- [X] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

### CODE REVIEW

**Comment by hugo-sid** [comment]
Hi Alberto.

First of all, thanks a lot for the detailed explanation.

Thanks for identifying the issue (Content pages are not filtered in recent posts) and creating the PR.

Everything looks good to me, apart from this:
- if you check the deploy preview link associated with this PR, the view all posts link on the homepage is missing.

I don't think your commits have caused this issue. I have to investigate.

**Comment by hugo-sid** [comment]
Ok, I see why the view all posts link on the homepage is missing.

https://github.com/hugo-sid/hugo-blog-awesome/blob/fd3d59c4c9fc0f291d275cc4de17b32098e6c121/layouts/index.html#L16-L20

So, the link is displayed if the length of `$posts` is greater than 5. It was visible earlier since, previously:

```go
{{ $posts := .Site.RegularPages.ByDate.Reverse }}
```
But with your commit, this has changed to:

```go
{{ $pagesToShow := where .Site.RegularPages "Type" "in" site.Params.mainSections }}
{{ $posts := $pagesToShow.ByDate.Reverse }}
```

As a result of this the about page is no longer counted and thus `$posts` equals to 5 (not greater than). Thus the link is missing.

**Comment by hugo-sid** [comment]
Thanks Alberto, for starring the repo & for creating the PR.

You have made a significant contribution to this theme.

Looking forward to more contributions from you.

Have a good day. Happy blogging 🙂

**Comment by boh717** [comment]
Thanks @hugo-sid 😄

**Pull request merged**
