### PR TITLE
fix: handle relative non-root baseURL

### PR DESCRIPTION
**Pull request by kusyka911**
## What problem does this PR solve?
This PR solve issue with deploying site using relative non-root base URL.
Instruction to reproduce:
1. build website with relative non-root base url
with config.toml
```toml
baseURL = '/kusyka/'
```
or with CLI options
```sh
hugo -b /kusyka/
```
3. Create deployment using local instillation of nginx (or you may use docker instead)
Example nginx configuration `/etc/nginx/nginx.conf`:
In this example we have default website in `/usr/share/nginx/html/` and hugo website in `/usr/share/nginx/kusyka/`
```conf
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    server {
            listen       80;
            server_name  localhost;

            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
    
            location /kusyka {
                root /usr/share/nginx/;
                index  index.html index.htm;
                error_page  404 /kusyka/404.html;
            }
}
```
4. try to visit website (better using another device) by remote IP (check firewall configuration if needed)
5. Pay attention to the result
base_url_issue

### Solution

- fonts not loaded
  * `head.html`
  place built css file to root of the website and rename to `style.css`
  * _font.scss
  use root relative URL for fonts
- icons not loaded
  * regenerated icons with [realfavicongenerator](https://realfavicongenerator.net/)
  * move all icons to `assets` directory and load them as a resource in `head.html` using `.RelPermalink`
  * `favicon.ico` placed to site root after build (some browser may request it on root by default) 
- make template for `site.webmanifest` and `browserconfig.xml` to fill them with all needed options
  * added more icons for windows tiles
  * added ability to customize some options using `params.webmanifest` and `params.browserconfig`

## Is this PR adding a new feature?
no

## Is this PR related to any issue or discussion?
no

## PR Checklist

- [x] I have verified that the code works as described/as intended.
- [ ] This change adds a social icon which has a permissive license to use it.
- [x] This change **does not** include any external library/resources.
- [x] This change **does not** include any unrelated scripts (e.g. bash and python scripts).
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

### CODE REVIEW

**Comment by kusyka911** [comment]
@hugo-sid I think there is possibility to make hugo template for `site.webmanifest`. I'll try to implement this solution.

**Comment by kusyka911** [comment]
@hugo-sid please review this

**Comment by hugo-sid** [comment]
Thanks for the hard work @kusyka911.

> I think I covered all possible scenarios. At least for me everything works good.

That's great.

If you feel, this PR is ready for review, could you please mark the PR as ready? Currently it's a draft PR.

**Comment by hugo-sid** [comment]
> This PR exceeds the recommended size of 200 lines. Kindly ensure that you are NOT addressing multiple issues in one PR. We recommend you to create atomic PRs which focus on a single change.

You may ignore this warning, since you are addressing a single issue in this PR.

**Comment by kusyka911** [comment]
> If you feel, this PR is ready for review, could you please mark the PR as ready for review? Currently it's a draft PR.

Done, also added docs.

**Review by hugo-sid — APPROVED** [review]
Thanks @kusyka911, for this new feature. I think this PR will fix https://github.com/hugo-sid/hugo-blog-awesome/issues/36.

Thanks for your willingness to improve this theme.

I appreciate your contribution.

**Pull request merged**
