### PR TITLE
added pt-br translation

### PR DESCRIPTION
**Pull request by devnull-hub-lab**
Added pt-br translation (i18n Internationalization)

### CODE REVIEW

**Review by hugo-sid — CHANGES_REQUESTED** [review]
@devnull-hub-lab thanks for adding pt-br i18n file.

Kindly note that you have completed one of the three steps required to add a new language. For further details, please refer to the contribution guidelines here:
https://github.com/hugo-sid/hugo-blog-awesome/blob/main/CONTRIBUTING.md#adding-a-new-language

**Comment by devnull-hub-lab** [comment]
Hi @hugo-sid 

Thanks for accepting PR.

Yes, I think (just my opinion) that if you include every translated language in hugo.toml, it could inflate hugo.toml unnecessarily, as most people only use one or two translations at most. My suggestion (if you accept it) would be to keep only 3 translations in hugo.toml and just add a comment with information that there are translations in other languages too, without necessarily replicating the codes in all translated languages.

In any case, if you prefer to keep all translated languages ​​in hugo.toml, replicating the menu code for them and including them in ExampleSite, let me know and I'll make the PR for these changes.

**Comment by hugo-sid** [comment]
Hi @devnull-hub-lab,

> In any case, if you prefer to keep all translated languages ​​in hugo.toml, replicating the menu code for them and including them in ExampleSite, let me know and I'll make the PR for these changes.

I prefer this way. Kindly proceed & make the necessary changes to this PR.

Please note that, you have to take care of the following:

- Add language specific configuration and parameters in `exampleSite/hugo.toml`
- Translate specific terms by creating a new language-specific file in the `i18n` directory
- Add translated content in `exampleSite/content` directory

**Review by devnull-hub-lab — COMMENTED** [review]
Yep, sure!
Its done.

**Review by hugo-sid — APPROVED** [review]
Thank you @devnull-hub-lab for adding pt-br translation.

**Pull request merged**
